version: "3.8"

services:
  mongodb:
    container_name: mongodb-replica
    image: mongo:latest
    command: --replSet rs0
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
